### ISSUE TITLE
Layout flow out of view unless drawer menu is activated

### ISSUE THREAD

**Issue by leocrawf** [NativeScript/template-drawer-navigation#21]
If one should use a simple layout like this: 
       `<GridLayout rows="auto, *, auto">
       <Label row="0" text="header" />
       <ScrollView row="1">
            /// whatever in here will scroll
        </ScrollView>
       <StackLayout row="2"> /// fixed footer <<<<
         //// whatever fixed in here
        </StackLayout>
      </GridLayout>`

part of the last row, row=2 would flow off the screen until the user activate the main menu by clicking the menu icon after which point the last row adjust and show as it should. I have tried this with many layout types including only stacklayout and got the same result. When I remove the RadsideDrawer component the issue is fixed and shows as expected. I ended up removing the RadsideDrawer component from all the pages .

**Comment by vegeorgi** [comment]
Hi @leocrawf

There are fixes in the nativescript ui connected with the RadSideDrawer scrolling, that will be released with the next version later this month.
Please wait until they are released. If you still experience this problem by then, you can log a bug in the official Nativescript UI repo for RadSideDrawer - [link](https://github.com/telerik/nativescript-ui-feedback). 

Regards
