### ISSUE TITLE
iOS Tap Event on the Hamburger

### ISSUE THREAD

**Issue by QuinnZillian** [NativeScript/template-drawer-navigation#24]
[2017-08-02.09-55-28.mp4.zip](https://github.com/NativeScript/template-drawer-navigation/files/1229656/2017-08-02.09-55-28.mp4.zip)
**Description:**  
On an iOS iPhone 6 emulator, the 'onTap' event on the hamburger navigation only works once.  Subsequent events require a 'tapAndSlide' to see the drawer navigation.

The JS, TS, and NG on the iOS device all exhibit the same behavior.

_See the video for a demo of what I'm experiencing..._

**NativeScript** 
  SideKick Version: 0.2.2-v.2017.8.9.3 (latest)
  NativeScript CLI version: 3.1.3
  CLI extension nativescript-cloud version: 0.11.7
  CLI extension nativescript-starter-kits version: 0.1.11

nativescript: 3.1.3
tns-core-modules: 3.1.1 
tns-android: 3.1.1
tns-ios: 3.1.0

**System** 
  Version:	macOS 10.12.6 (16G29)
  Kernel Version:	Darwin 16.7.0

**Model Name:**	MacBook Pro
  Model Identifier:	MacBookPro9,2
  Processor Name:	Intel Core i5
  Processor Speed:	2.5 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Memory:	8 GB

**Xcode**
  Version 8.3.3 (8E3004b)

**Node**
  Version v6.11.2

**Comment by manoldonev** [comment]
Hello @QuinnZillian,

Indeed this is a known issue in the Drawer component. We have already addressed it and a fix will be available in the next version of the Progress Nativescript UI suite.
