### ISSUE TITLE
Navigation Lags 

### ISSUE THREAD

**Issue by tsbignoob** [NativeScript/template-drawer-navigation#29]
When testing template-drawer-navigation-ng on actual hardware/device, Accessing pages via the side drawer component lags randomly for 2-3 seconds before the touch even registers.  Try opening different pages from the side menu, the lag will show up after 5-6 page changes. 

Tested on snapdragon 435, 650, 820, with plenty of RAM available. Same results. 

Note: I didn't notice the same effect on template-tab-navigation.

**Comment by manoldonev** [comment]
@tsbignoob cannot reproduce the erroneous behavior when testing on Nexus 5 device (snapdragon 800). Could you confirm you are using the latest version of the CLI / runtime (3.2.0)?
- CLI: (run `tns --version` to fetch it)
- Runtime(s): (look for the `"tns-android"` property in the `package.json` file of your project)

**Comment by manoldonev** [comment]
Also, can you specify the Android versions of the devices you are testing on?

**Comment by tsbignoob** [comment]
- "tns --version"  returns 3.2.0 
- "tns-android" section also shows "version": "3.2.0"

Android versions: 6.0.1, 5.1.1, LineageOS 13(6.x), MIUI 8.5(6.x) 

I did some additional testing on a chinese intel cherry trail tablet and couldn't reproduce it there or on androidx86 emulator, but all the phones showed the symptom. Rather confusing.

**Comment by manoldonev** [comment]
This behavior might be related to garbage collection -- you can try the experimental feature described [here](https://www.nativescript.org/blog/announcing-the-release-of-nativescript-3.2#gc) to see whether it makes any difference on your physical testing devices.

**Comment by tsbignoob** [comment]
Tried the experimental flags during the weekend on the devices, but it didn't solve the problem. I don't know enough to dive into all the timings trace described in the article. Can the problem be on the drawer component side?

**Comment by manoldonev** [comment]
I am still unable to reproduce the behavior in our local tests and it is difficult to pinpoint the root cause like that but the template itself is pretty lean and basic so I doubt the problem would be related to the app template itself.

**Comment by tsbignoob** [comment]
Thank you for looking into this. I'll go ahead and build up my app using the template. Will report back if the problem showed up later on.
