### ISSUE TITLE
Webpack Can't resolve './app.css'

### ISSUE THREAD

**Issue by aboganas** [NativeScript/template-drawer-navigation#47]
Since the template has specific `app.ios.scss` and `app.android.scss` , I have problem using web pack as it gives the following error 
``` ERROR in Entry module not found: Error: Can't resolve './app.css' in '/Users/myUsername/myDemo/app ```

How can I enable web pack with this tamplate?

**Comment by MartoYankov** [comment]
hay @aboganas 

The current implementation of {N} and the dev-webpack plugin don't work well with .scss files. Currently, you can change the mainSheet entry in the webpack config to include the platform, but there will be problems with the drawer. There is a workaround where you can move the styles of the drawer to the app.scss files and it should work. Here is an example webpack.config file that should resolve app.css properly - https://gist.github.com/MartoYankov/476a9b12fe8addb5cc7ca1a1144706fe.

We are working on fixing these issues and with the next release of the templates and {N} we will provide built-in webpack configurations.

**Comment by manoldonev** [comment]
@aboganas we have now published to npm version@3.4.1 of this template that supports webpack bundling out-of-the-box.
